<?php
/**
 * ItemApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WeProov Api
 *
 * WeProov public API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: support@weproov.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * ItemApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation itemGet
     *
     * Allows you to retrieve the items list
     *
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     * @param  string $find filter by id of category (optional)
     * @param  int $limit Max: 50 (optional)
     * @param  int $offset offset (optional)
     * @param  \DateTime $created_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $updated_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ItemShort[]
     */
    public function itemGet($lang = null, $find = null, $limit = null, $offset = null, $created_at = null, $updated_at = null)
    {
        list($response) = $this->itemGetWithHttpInfo($lang, $find, $limit, $offset, $created_at, $updated_at);
        return $response;
    }

    /**
     * Operation itemGetWithHttpInfo
     *
     * Allows you to retrieve the items list
     *
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     * @param  string $find filter by id of category (optional)
     * @param  int $limit Max: 50 (optional)
     * @param  int $offset offset (optional)
     * @param  \DateTime $created_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $updated_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ItemShort[], HTTP status code, HTTP response headers (array of strings)
     */
    public function itemGetWithHttpInfo($lang = null, $find = null, $limit = null, $offset = null, $created_at = null, $updated_at = null)
    {
        $returnType = '\Swagger\Client\Model\ItemShort[]';
        $request = $this->itemGetRequest($lang, $find, $limit, $offset, $created_at, $updated_at);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ItemShort[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation itemGetAsync
     *
     * Allows you to retrieve the items list
     *
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     * @param  string $find filter by id of category (optional)
     * @param  int $limit Max: 50 (optional)
     * @param  int $offset offset (optional)
     * @param  \DateTime $created_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $updated_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemGetAsync($lang = null, $find = null, $limit = null, $offset = null, $created_at = null, $updated_at = null)
    {
        return $this->itemGetAsyncWithHttpInfo($lang, $find, $limit, $offset, $created_at, $updated_at)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation itemGetAsyncWithHttpInfo
     *
     * Allows you to retrieve the items list
     *
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     * @param  string $find filter by id of category (optional)
     * @param  int $limit Max: 50 (optional)
     * @param  int $offset offset (optional)
     * @param  \DateTime $created_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $updated_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemGetAsyncWithHttpInfo($lang = null, $find = null, $limit = null, $offset = null, $created_at = null, $updated_at = null)
    {
        $returnType = '\Swagger\Client\Model\ItemShort[]';
        $request = $this->itemGetRequest($lang, $find, $limit, $offset, $created_at, $updated_at);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'itemGet'
     *
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     * @param  string $find filter by id of category (optional)
     * @param  int $limit Max: 50 (optional)
     * @param  int $offset offset (optional)
     * @param  \DateTime $created_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $updated_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function itemGetRequest($lang = null, $find = null, $limit = null, $offset = null, $created_at = null, $updated_at = null)
    {

        $resourcePath = '/item';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($lang !== null) {
            $queryParams['lang'] = ObjectSerializer::toQueryValue($lang);
        }
        // query params
        if ($find !== null) {
            $queryParams['find'] = ObjectSerializer::toQueryValue($find);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }
        // query params
        if ($created_at !== null) {
            $queryParams['created_at'] = ObjectSerializer::toQueryValue($created_at);
        }
        // query params
        if ($updated_at !== null) {
            $queryParams['updated_at'] = ObjectSerializer::toQueryValue($updated_at);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation itemIdDelete
     *
     * Allows you to delete an item
     *
     * @param  int $id id of item (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Success
     */
    public function itemIdDelete($id)
    {
        list($response) = $this->itemIdDeleteWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation itemIdDeleteWithHttpInfo
     *
     * Allows you to delete an item
     *
     * @param  int $id id of item (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Success, HTTP status code, HTTP response headers (array of strings)
     */
    public function itemIdDeleteWithHttpInfo($id)
    {
        $returnType = '\Swagger\Client\Model\Success';
        $request = $this->itemIdDeleteRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Success',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation itemIdDeleteAsync
     *
     * Allows you to delete an item
     *
     * @param  int $id id of item (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemIdDeleteAsync($id)
    {
        return $this->itemIdDeleteAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation itemIdDeleteAsyncWithHttpInfo
     *
     * Allows you to delete an item
     *
     * @param  int $id id of item (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemIdDeleteAsyncWithHttpInfo($id)
    {
        $returnType = '\Swagger\Client\Model\Success';
        $request = $this->itemIdDeleteRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'itemIdDelete'
     *
     * @param  int $id id of item (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function itemIdDeleteRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling itemIdDelete'
            );
        }

        $resourcePath = '/item/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation itemIdGet
     *
     * Allows you to retrieve an item
     *
     * @param  int $id id of item (required)
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Item
     */
    public function itemIdGet($id, $lang = null)
    {
        list($response) = $this->itemIdGetWithHttpInfo($id, $lang);
        return $response;
    }

    /**
     * Operation itemIdGetWithHttpInfo
     *
     * Allows you to retrieve an item
     *
     * @param  int $id id of item (required)
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Item, HTTP status code, HTTP response headers (array of strings)
     */
    public function itemIdGetWithHttpInfo($id, $lang = null)
    {
        $returnType = '\Swagger\Client\Model\Item';
        $request = $this->itemIdGetRequest($id, $lang);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Item',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation itemIdGetAsync
     *
     * Allows you to retrieve an item
     *
     * @param  int $id id of item (required)
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemIdGetAsync($id, $lang = null)
    {
        return $this->itemIdGetAsyncWithHttpInfo($id, $lang)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation itemIdGetAsyncWithHttpInfo
     *
     * Allows you to retrieve an item
     *
     * @param  int $id id of item (required)
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemIdGetAsyncWithHttpInfo($id, $lang = null)
    {
        $returnType = '\Swagger\Client\Model\Item';
        $request = $this->itemIdGetRequest($id, $lang);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'itemIdGet'
     *
     * @param  int $id id of item (required)
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function itemIdGetRequest($id, $lang = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling itemIdGet'
            );
        }

        $resourcePath = '/item/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($lang !== null) {
            $queryParams['lang'] = ObjectSerializer::toQueryValue($lang);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation itemIdReportGet
     *
     * Allows you to retrieve the reports list that is linked to a specific item
     *
     * @param  int $id id of item (required)
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     * @param  string $find filter by id of category (optional)
     * @param  string $custom_ref filter by custom reference (optional)
     * @param  int $category_id filter by id of category (optional)
     * @param  int $sub_category_id filter by id of subcategory (optional)
     * @param  string $state filter by id of category (optional)
     * @param  int $template_id template of id used (optional)
     * @param  int $limit Max: 50 (optional)
     * @param  int $offset offset (optional)
     * @param  \DateTime $created_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $finished_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $dropoff_finished_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ReportShort[]
     */
    public function itemIdReportGet($id, $lang = null, $find = null, $custom_ref = null, $category_id = null, $sub_category_id = null, $state = null, $template_id = null, $limit = null, $offset = null, $created_at = null, $finished_at = null, $dropoff_finished_at = null)
    {
        list($response) = $this->itemIdReportGetWithHttpInfo($id, $lang, $find, $custom_ref, $category_id, $sub_category_id, $state, $template_id, $limit, $offset, $created_at, $finished_at, $dropoff_finished_at);
        return $response;
    }

    /**
     * Operation itemIdReportGetWithHttpInfo
     *
     * Allows you to retrieve the reports list that is linked to a specific item
     *
     * @param  int $id id of item (required)
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     * @param  string $find filter by id of category (optional)
     * @param  string $custom_ref filter by custom reference (optional)
     * @param  int $category_id filter by id of category (optional)
     * @param  int $sub_category_id filter by id of subcategory (optional)
     * @param  string $state filter by id of category (optional)
     * @param  int $template_id template of id used (optional)
     * @param  int $limit Max: 50 (optional)
     * @param  int $offset offset (optional)
     * @param  \DateTime $created_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $finished_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $dropoff_finished_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ReportShort[], HTTP status code, HTTP response headers (array of strings)
     */
    public function itemIdReportGetWithHttpInfo($id, $lang = null, $find = null, $custom_ref = null, $category_id = null, $sub_category_id = null, $state = null, $template_id = null, $limit = null, $offset = null, $created_at = null, $finished_at = null, $dropoff_finished_at = null)
    {
        $returnType = '\Swagger\Client\Model\ReportShort[]';
        $request = $this->itemIdReportGetRequest($id, $lang, $find, $custom_ref, $category_id, $sub_category_id, $state, $template_id, $limit, $offset, $created_at, $finished_at, $dropoff_finished_at);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ReportShort[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation itemIdReportGetAsync
     *
     * Allows you to retrieve the reports list that is linked to a specific item
     *
     * @param  int $id id of item (required)
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     * @param  string $find filter by id of category (optional)
     * @param  string $custom_ref filter by custom reference (optional)
     * @param  int $category_id filter by id of category (optional)
     * @param  int $sub_category_id filter by id of subcategory (optional)
     * @param  string $state filter by id of category (optional)
     * @param  int $template_id template of id used (optional)
     * @param  int $limit Max: 50 (optional)
     * @param  int $offset offset (optional)
     * @param  \DateTime $created_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $finished_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $dropoff_finished_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemIdReportGetAsync($id, $lang = null, $find = null, $custom_ref = null, $category_id = null, $sub_category_id = null, $state = null, $template_id = null, $limit = null, $offset = null, $created_at = null, $finished_at = null, $dropoff_finished_at = null)
    {
        return $this->itemIdReportGetAsyncWithHttpInfo($id, $lang, $find, $custom_ref, $category_id, $sub_category_id, $state, $template_id, $limit, $offset, $created_at, $finished_at, $dropoff_finished_at)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation itemIdReportGetAsyncWithHttpInfo
     *
     * Allows you to retrieve the reports list that is linked to a specific item
     *
     * @param  int $id id of item (required)
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     * @param  string $find filter by id of category (optional)
     * @param  string $custom_ref filter by custom reference (optional)
     * @param  int $category_id filter by id of category (optional)
     * @param  int $sub_category_id filter by id of subcategory (optional)
     * @param  string $state filter by id of category (optional)
     * @param  int $template_id template of id used (optional)
     * @param  int $limit Max: 50 (optional)
     * @param  int $offset offset (optional)
     * @param  \DateTime $created_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $finished_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $dropoff_finished_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemIdReportGetAsyncWithHttpInfo($id, $lang = null, $find = null, $custom_ref = null, $category_id = null, $sub_category_id = null, $state = null, $template_id = null, $limit = null, $offset = null, $created_at = null, $finished_at = null, $dropoff_finished_at = null)
    {
        $returnType = '\Swagger\Client\Model\ReportShort[]';
        $request = $this->itemIdReportGetRequest($id, $lang, $find, $custom_ref, $category_id, $sub_category_id, $state, $template_id, $limit, $offset, $created_at, $finished_at, $dropoff_finished_at);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'itemIdReportGet'
     *
     * @param  int $id id of item (required)
     * @param  \Swagger\Client\Model\Local $lang Response language (optional)
     * @param  string $find filter by id of category (optional)
     * @param  string $custom_ref filter by custom reference (optional)
     * @param  int $category_id filter by id of category (optional)
     * @param  int $sub_category_id filter by id of subcategory (optional)
     * @param  string $state filter by id of category (optional)
     * @param  int $template_id template of id used (optional)
     * @param  int $limit Max: 50 (optional)
     * @param  int $offset offset (optional)
     * @param  \DateTime $created_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $finished_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     * @param  \DateTime $dropoff_finished_at range of datetime in RFC3339 separate by &#x27;,&#x27; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function itemIdReportGetRequest($id, $lang = null, $find = null, $custom_ref = null, $category_id = null, $sub_category_id = null, $state = null, $template_id = null, $limit = null, $offset = null, $created_at = null, $finished_at = null, $dropoff_finished_at = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling itemIdReportGet'
            );
        }

        $resourcePath = '/item/{id}/report';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($lang !== null) {
            $queryParams['lang'] = ObjectSerializer::toQueryValue($lang);
        }
        // query params
        if ($find !== null) {
            $queryParams['find'] = ObjectSerializer::toQueryValue($find);
        }
        // query params
        if ($custom_ref !== null) {
            $queryParams['custom_ref'] = ObjectSerializer::toQueryValue($custom_ref);
        }
        // query params
        if ($category_id !== null) {
            $queryParams['category_id'] = ObjectSerializer::toQueryValue($category_id);
        }
        // query params
        if ($sub_category_id !== null) {
            $queryParams['sub_category_id'] = ObjectSerializer::toQueryValue($sub_category_id);
        }
        // query params
        if ($state !== null) {
            $queryParams['state'] = ObjectSerializer::toQueryValue($state);
        }
        // query params
        if ($template_id !== null) {
            $queryParams['template_id'] = ObjectSerializer::toQueryValue($template_id);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }
        // query params
        if ($created_at !== null) {
            $queryParams['created_at'] = ObjectSerializer::toQueryValue($created_at);
        }
        // query params
        if ($finished_at !== null) {
            $queryParams['finished_at'] = ObjectSerializer::toQueryValue($finished_at);
        }
        // query params
        if ($dropoff_finished_at !== null) {
            $queryParams['dropoff_finished_at'] = ObjectSerializer::toQueryValue($dropoff_finished_at);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
