<?php
/**
 * MissionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WeProov Api
 *
 * WeProov public API
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: support@weproov.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * MissionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MissionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for missionGet
     *
     * Retrieval of all sent missions.
     *
     */
    public function testMissionGet()
    {
    }

    /**
     * Test case for missionIdDelete
     *
     * Delete a sent mission.
     *
     */
    public function testMissionIdDelete()
    {
    }

    /**
     * Test case for missionIdGet
     *
     * Retrieval of a single mission.
     *
     */
    public function testMissionIdGet()
    {
    }

    /**
     * Test case for missionIdPost
     *
     * Mission update.
     *
     */
    public function testMissionIdPost()
    {
    }

    /**
     * Test case for missionPut
     *
     * Mission creation.
     *
     */
    public function testMissionPut()
    {
    }
}
